[package]
name = "ritsu"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
futures-task = "0.3"
futures-util = "0.3"
slab = "*"
bytes = "0.5"
socket2 = "*"
async-trait = "*"

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = "0.3"

[dev-dependencies]
anyhow = "*"
