[package]
name = "ritsu"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"
futures = "0.3"
slab = "*"

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = { package = "linux-io-uring", git = "https://github.com/quininer/linux-io-uring" }
